"""
HABESHAGO PostgreSQL Schema Authority

Provides PostgreSQL-specific schema translation and,
later, fresh-schema initialization.

Legacy SQLite migrations do not belong here.

Canonical principle:

    One Business Event
        -> One Record
        -> One Persistence Authority
"""


import re


class PostgreSQLSchemaError(
    RuntimeError
):
    """
    Raised when canonical HABESHAGO schema translation
    cannot be performed safely.
    """


def translate_sqlite_schema_statement(
    statement: str,
) -> str:
    """
    Translate one fresh HABESHAGO SQLite DDL statement
    into PostgreSQL-compatible DDL.

    This translator is intentionally limited to canonical
    fresh-schema constructs. Legacy PRAGMA, ALTER-based
    migrations, and INSERT OR IGNORE backfills are rejected.
    """

    if not isinstance(
        statement,
        str,
    ):
        raise TypeError(
            "Schema statement must be a string."
        )

    translated = statement.strip()

    if not translated:
        raise PostgreSQLSchemaError(
            "Schema statement cannot be empty."
        )

    upper = translated.upper()

    forbidden = (
        "PRAGMA ",
        "ALTER TABLE ",
        "INSERT OR IGNORE ",
    )

    for marker in forbidden:

        if marker in upper:
            raise PostgreSQLSchemaError(
                "Legacy SQLite migration SQL cannot enter "
                "the PostgreSQL fresh-schema authority: "
                + marker.strip()
            )

    # SQLite:
    #
    #     id INTEGER PRIMARY KEY AUTOINCREMENT
    #
    # PostgreSQL:
    #
    #     id INTEGER GENERATED BY DEFAULT
    #        AS IDENTITY PRIMARY KEY
    translated = re.sub(
        r"""
        \bINTEGER
        \s+PRIMARY\s+KEY
        \s+AUTOINCREMENT\b
        """,
        (
            "INTEGER GENERATED BY DEFAULT "
            "AS IDENTITY PRIMARY KEY"
        ),
        translated,
        flags=(
            re.IGNORECASE
            | re.VERBOSE
        ),
    )

    # SQLite REAL values use double-precision floating-point
    # storage. PostgreSQL REAL is only single precision and
    # would silently reduce HABESHAGO coordinate, distance,
    # fare, commission, earnings, and rating precision.
    #
    # Preserve the canonical SQLite numeric value surface by
    # translating REAL columns to PostgreSQL DOUBLE PRECISION.
    translated = re.sub(
        r"\bREAL\b",
        "DOUBLE PRECISION",
        translated,
        flags=re.IGNORECASE,
    )

    # External HABESHAGO platform identities may exceed
    # PostgreSQL's signed 32-bit INTEGER range.
    #
    # Keep internal HABESHAGO generated row IDs as INTEGER
    # IDENTITY columns while promoting only canonical
    # external identity columns to BIGINT.
    bigint_columns = {
        "passengers": {
            "telegram_id",
        },
        "drivers": {
            "telegram_id",
        },
        "vehicles": {
            "driver_id",
        },
        "rides": {
            "passenger_id",
            "driver_id",
        },
        "ride_offers": {
            "passenger_id",
            "driver_id",
        },
        "driver_admin_actions": {
            "driver_id",
            "actor_id",
        },
        "payment_requests": {
            "payer_id",
        },
        "payment_transactions": {
            "payer_id",
        },
        "passenger_places": {
            "passenger_id",
        },
    }

    table_match = re.search(
        r"""
        CREATE\s+TABLE
        \s+(?:IF\s+NOT\s+EXISTS\s+)?
        ([A-Za-z_][A-Za-z0-9_]*)
        """,
        translated,
        flags=(
            re.IGNORECASE
            | re.VERBOSE
        ),
    )

    if table_match:

        table_name = (
            table_match
            .group(1)
            .lower()
        )

        for column_name in bigint_columns.get(
            table_name,
            set(),
        ):

            pattern = (
                rf"(?m)^"
                rf"(\s*{re.escape(column_name)}\s+)"
                rf"INTEGER\b"
            )

            translated, count = re.subn(
                pattern,
                r"\1BIGINT",
                translated,
                count=1,
                flags=re.IGNORECASE,
            )

            if count != 1:
                raise PostgreSQLSchemaError(
                    "Expected exactly one canonical "
                    "platform identity column for BIGINT "
                    "translation: "
                    f"{table_name}.{column_name}"
                )

    return translated


def extract_canonical_fresh_schema():
    """
    Extract HABESHAGO's canonical fresh-schema DDL from
    create_tables() without executing SQLite migrations.

    Returns:
        tuple[list[str], list[str]]:
            PostgreSQL-compatible table statements and
            PostgreSQL-compatible index statements.
    """

    import ast

    from pathlib import Path

    database_path = Path(
        "app/database/database.py"
    )

    database_text = database_path.read_text(
        encoding="utf-8"
    )

    tree = ast.parse(
        database_text
    )

    create_tables_node = None

    for node in tree.body:

        if (
            isinstance(
                node,
                ast.FunctionDef,
            )
            and node.name == "create_tables"
        ):
            create_tables_node = node
            break

    if create_tables_node is None:
        raise PostgreSQLSchemaError(
            "Canonical create_tables() authority "
            "was not found."
        )

    table_statements = []
    index_statements = []

    for node in ast.walk(
        create_tables_node
    ):

        if not isinstance(
            node,
            ast.Call,
        ):
            continue

        if not isinstance(
            node.func,
            ast.Attribute,
        ):
            continue

        if node.func.attr != "execute":
            continue

        if not node.args:
            continue

        first_arg = node.args[0]

        if not isinstance(
            first_arg,
            ast.Constant,
        ):
            continue

        if not isinstance(
            first_arg.value,
            str,
        ):
            continue

        statement = (
            first_arg.value.strip()
        )

        upper = statement.upper()

        if upper.startswith(
            "CREATE TABLE"
        ):
            table_statements.append(
                translate_sqlite_schema_statement(
                    statement
                )
            )

        elif (
            upper.startswith(
                "CREATE INDEX"
            )
            or upper.startswith(
                "CREATE UNIQUE INDEX"
            )
        ):
            index_statements.append(
                translate_sqlite_schema_statement(
                    statement
                )
            )

    if len(table_statements) != 15:
        raise PostgreSQLSchemaError(
            "Expected 15 canonical HABESHAGO "
            "table definitions, found "
            f"{len(table_statements)}."
        )

    if len(index_statements) != 43:
        raise PostgreSQLSchemaError(
            "Expected 43 canonical HABESHAGO "
            "index definitions, found "
            f"{len(index_statements)}."
        )

    return (
        table_statements,
        index_statements,
    )


def create_postgresql_tables(
    connection,
):
    """
    Create the complete fresh HABESHAGO PostgreSQL schema.

    This initializer intentionally creates only the current
    canonical schema. Historical SQLite migrations and data
    backfills are excluded.

    The caller supplies an established PostgreSQL-compatible
    connection so connection authority remains centralized.
    """

    table_statements, index_statements = (
        extract_canonical_fresh_schema()
    )

    cursor = connection.cursor()

    try:
        for statement in table_statements:
            cursor.execute(
                statement
            )

        for statement in index_statements:
            cursor.execute(
                statement
            )

        connection.commit()

    except Exception:
        connection.rollback()
        raise

    finally:
        cursor.close()

    return {
        "tables_created": len(
            table_statements
        ),
        "indexes_created": len(
            index_statements
        ),
    }

