REQUESTED = "REQUESTED"

ACCEPTED = "ACCEPTED"

DRIVER_ARRIVING = "DRIVER_ARRIVING"

DRIVER_ARRIVED = "DRIVER_ARRIVED"

TRIP_STARTED = "TRIP_STARTED"

TRIP_COMPLETED = "TRIP_COMPLETED"

RATED = "RATED"